### ISSUE TITLE
Algorithm: Use version hierarchies

### ISSUE THREAD

**Issue by pradal** [VersionClimber/VersionClimber#74]
Versions of packages use semantic versionning.
The algorithm will explore the packages using the hierarchy (major first then major.minor then ...).

**TODO**:
- integrate the new hierarchical algorithm into VersionClimber
- add an option to the configuration file

**Comment by pradal** [comment]
Use the version with demand and supply mini-sets.
Look for a strategy to infer demand-constant and supply-constant

**Comment by dennisshasha** [comment]
Dear Christophe,
Great. Does that mean you've integrated the new version?
Also, even better than inferring demand-constant and supply-constant
is inferring total demand and total supply from the runtime.
Warmly,
Dennis

**Comment by pradal** [comment]
Fixed in #75
